CREATE PROCEDURE pr_localidadProvincia
    @nombreExpo VARCHAR(50),
    @cadenaSalida VARCHAR(70) OUTPUT
AS
BEGIN
SELECT @cadenaSalida = CONCAT(l.nome,'(', p.nome, ')') FROM EXPOSICION e
JOIN LOCALIDADE l ON l.CODIGO = 
	(SELECT COD_LOCALIDADE FROM EXPOSICION WHERE NOME = @nombreExpo)
JOIN PROVINCIA p ON p.CODIGO = 
	(SELECT COD_PROVINCIA FROM EXPOSICION WHERE NOME = @nombreExpo)
END;
GO